### PR TITLE
Don't include .git Directoy in Bundle

### PR DESCRIPTION
**Pull request by Ronnie-personal**
This PR addresses #92

### CODE REVIEW

**Comment by Ronnie-personal** [comment]
@anderseknert 

I'm unable to make 'opa eval --ignore' work from the OPA CLI. When I tried adding the '--ignore' option, it seems that nothing gets ignored. Furthermore, when testing the modified extension using 'OPA: evaluate package,' it evaluates the policy in the current editor, and the '--ignore' option (configured in the extension settings under 'opa.bundleIgnorePaths') is not being honored.

Thanks and appreciate if you could help.

**Comment by anderseknert** [comment]
Thanks for investigating, @Ronnie-personal. That does seem like a bug in OPA. We've had similar issues reported and fixed for the [bundle](https://github.com/open-policy-agent/opa/issues/2944) command as well as the [test](https://github.com/open-policy-agent/opa/issues/4593) command (and perhaps still do there) in the past. 

I've created an [issue in OPA](https://github.com/open-policy-agent/opa/issues/6358) for this. If you have the time, help with that would be much appreciated!

**Comment by Ronnie-personal** [comment]
@anderseknert 
Sorry about the late response, I took some time off recently.

Thanks for sharing the insights!

Yes, I'm happy to work on the OPA issue.

**Comment by anderseknert** [comment]
Thanks @Ronnie-personal. I think the issue in OPA could be a bit more difficult than what it seems, so let me know if you need any help.

**Comment by anderseknert** [comment]
As the issue in OPA around ignore directives is still blocking, and from what I've seen, there's no simple fix that wouldn't break API compatibility available... I'll close this for the time being :/ 

@Ronnie-personal I'd love to see more of your contributions! If you'd join our [slack community](https://communityinviter.com/apps/styracommunity/signup), I'd love to talk more :)

**Pull request closed without merging**
